In [2]:
import numpy as np
import os

In [3]:
a = np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))

print(a)





[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
a.shape

(4, 3)

In [5]:
from pathlib import Path

print()



In [6]:
# Create an array of numbers from 1 to 9
arr = np.arange(1, 10)

# Reshape the array into a 3x3 array
array_3x3 = arr.reshape(3, 3)

# Print the array
print(array_3x3)

print(np.mean(array_3x3, axis=0))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]


In [7]:
v = np.arange(1,5)
print(v)

print("regular mean")
print(np.mean(v))

print("column mean")
print(np.mean(v, axis=0))


[1 2 3 4]
regular mean
2.5
column mean
2.5


In [8]:
new = np.array(([1,2],[3,4],[5,6]))

print(new)
print(new.shape)

print(new.shape[0])


[[1 2]
 [3 4]
 [5 6]]
(3, 2)
3


In [15]:
import numpy as np

def getmatrix(a, loc):
  """
  Gets a contiguous matrix from an N-dimensional array.

  Args:
      a (N-dimensional array): The input array.
      loc (Mx1 vector): The indices into the array to locate the matrix of interest.
                          M can be N, N-1, or N-2.

  Returns:
      y (KxL matrix or 1xL matrix or scalar): The extracted matrix or scalar value.
          K is the size of the second fastest moving dimension, and L is the size
          of the fastest moving dimension.

  Raises:
      ValueError: If the dimensions of `loc` are not compatible with `a`.
  """
    
  # Handle edge cases: M = N (extract entire array)
  if loc.shape[0] == a.ndim:
    return a

  # Handle M = N-1 (extract a subarray along the last dimension)
  if loc.shape[0] == a.ndim - 1:
    sliced_array = a[tuple(loc)]
    if sliced_array.ndim == 1:
      return sliced_array.reshape(1, -1)  # Ensure row vector for consistency
    else:
      return sliced_array

  # Handle M = N-2 (extract a submatrix along the last two dimensions)
  if loc.shape[0] == a.ndim - 2:
    return a[tuple(loc)]

  # Raise an error for unsupported cases (M < N-2 or M > N)
  raise ValueError("Unsupported value for M. loc must have length N, N-1, or N-2.")

# Example usage:

_="""
arr = np.arange(24).reshape(2, 3, 4)
loc1 = np.array([0, 1, 2])  # Extract entire array (M = N)
loc2 = np.array([0, 1])    # Extract subarray along last dimension (M = N-1)
loc3 = np.array([0])       # Extract submatrix along last two dimensions (M = N-2)

result1 = getmatrix(arr, loc1)
result2 = getmatrix(arr, loc2)
result3 = getmatrix(arr, loc3)

print(result1)
print(result2)
print(result3)"""

a = np.arange(1, 19).reshape(3, 3, 2)

print(getmatrix(a, np.array([1])))


[[ 7  8]
 [ 9 10]
 [11 12]]
