In [29]:
import numpy as np
import os

In [30]:
a = np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))

print(a)





[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
a.shape

(4, 3)

In [32]:
def load_file(filename, subdir="/iofiles/"):
  # Construct the full path to the file
  
  fn = os.path.join(os.path.dirname(__file__), 'TODO') # Lesson hard learned: Directory name stuff doesn't work properly
  # in .ipynb-files. 

  filepath = os.path.join(subdir, filename)

  try:
    data = np.loadtxt(filepath, dtype=float)
    return data
  except FileNotFoundError:
    print(f"Error: File '{filepath}' not found.")
    return None
  
print(load_file("totKS.txt"))



NameError: name '__file__' is not defined

In [36]:
from pathlib import Path

print()



NameError: name '__file__' is not defined