In [1]:
import numpy as np
import os

In [2]:
a = np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))

print(a)


print(np.version.version)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
1.26.4


In [3]:
def fill_missing_values(x, age_seq2):
  """
  Fills missing values (represented by `mv`) in `x` using linear interpolation
  based on `age_seq2`.

  Args:
      x: (array-like) Data array with missing values.
      age_seq2: (array-like) Age sequence corresponding to data points in `x`.

  Returns:
      array-like: The array `x` with missing values filled using interpolation.
  """

  mv = np.nan  # Missing value representation
  rn = len(x)  # Number of rows

  for i in range(1, rn):
    # Check if current element is missing and previous element is valid
    if np.isnan(x[i]) and not np.isnan(x[i - 1]):
      j = i + 1
      # Find the next valid element after the missing one
      while j < rn and np.isnan(x[j]):
        j += 1

      # If a valid element is found within the data range
      if j <= rn:
        # Calculate interpolation fraction
        frac = (age_seq2[i] - age_seq2[i - 1]) / (age_seq2[j] - age_seq2[i - 1])
        # Interpolate the missing value
        x[i] = x[i - 1] + frac * (x[j] - x[i - 1])

  return x

# Example usage
x = np.array([1, np.nan, 3, 4, np.nan, 6])
age_seq2 = np.arange(1, len(x) + 1)

filled_x = fill_missing_values(x.copy(), age_seq2)
print(filled_x)  # Output: [ 1.  2.  3.  4.  5.  6. ]

[1. 2. 3. 4. 5. 6.]


In [4]:
a.shape

(4, 3)

In [5]:
from pathlib import Path

print()



In [6]:
# Create an array of numbers from 1 to 9
arr = np.arange(1, 10)

# Reshape the array into a 3x3 array
array_3x3 = arr.reshape(3, 3)

# Print the array
print(array_3x3)

print(np.mean(array_3x3, axis=0))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]


In [7]:
v = np.arange(1,5)
print(v)

print("regular mean")
print(np.mean(v))

print("column mean")
print(np.mean(v, axis=0))


[1 2 3 4]
regular mean
2.5
column mean
2.5


In [8]:
new = np.array(([1,2],[3,4],[5,6]))

print(new)
print(new.shape)

print(new.shape[0])


[[1 2]
 [3 4]
 [5 6]]
(3, 2)
3


In [9]:
import numpy as np

def getmatrix(a, loc):
  """
  Gets a contiguous matrix from an N-dimensional array.

  Args:
      a (N-dimensional array): The input array.
      loc (Mx1 vector): The indices into the array to locate the matrix of interest.
                          M can be N, N-1, or N-2.

  Returns:
      y (KxL matrix or 1xL matrix or scalar): The extracted matrix or scalar value.
          K is the size of the second fastest moving dimension, and L is the size
          of the fastest moving dimension.

  Raises:
      ValueError: If the dimensions of `loc` are not compatible with `a`.
  """
    
  # Handle edge cases: M = N (extract entire array)
  if loc.shape[0] == a.ndim:
    return a

  # Handle M = N-1 (extract a subarray along the last dimension)
  if loc.shape[0] == a.ndim - 1:
    sliced_array = a[tuple(loc)]
    if sliced_array.ndim == 1:
      return sliced_array.reshape(1, -1)  # Ensure row vector for consistency
    else:
      return sliced_array

  # Handle M = N-2 (extract a submatrix along the last two dimensions)
  if loc.shape[0] == a.ndim - 2:
    return a[tuple(loc)]

  # Raise an error for unsupported cases (M < N-2 or M > N)
  raise ValueError("Unsupported value for M. loc must have length N, N-1, or N-2.")

# Example usage:

_="""
arr = np.arange(24).reshape(2, 3, 4)
loc1 = np.array([0, 1, 2])  # Extract entire array (M = N)
loc2 = np.array([0, 1])    # Extract subarray along last dimension (M = N-1)
loc3 = np.array([0])       # Extract submatrix along last two dimensions (M = N-2)

result1 = getmatrix(arr, loc1)
result2 = getmatrix(arr, loc2)
result3 = getmatrix(arr, loc3)

print(result1)
print(result2)
print(result3)"""

a = np.arange(1, 19).reshape(3, 3, 2)

print(getmatrix(a, np.array([1])))


[[ 7  8]
 [ 9 10]
 [11 12]]
