In [2]:
import numpy as np
import os

In [3]:
a = np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))

print(a)





[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
a.shape

(4, 3)

In [5]:
from pathlib import Path

print()



In [6]:
# Create an array of numbers from 1 to 9
arr = np.arange(1, 10)

# Reshape the array into a 3x3 array
array_3x3 = arr.reshape(3, 3)

# Print the array
print(array_3x3)

print(np.mean(array_3x3, axis=0))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]


In [7]:
v = np.arange(1,5)
print(v)

print("regular mean")
print(np.mean(v))

print("column mean")
print(np.mean(v, axis=0))


[1 2 3 4]
regular mean
2.5
column mean
2.5


In [10]:
new = np.array(([1,2],[3,4],[5,6]))

print(new)
print(new.shape)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)
